### ISSUE TITLE
Ped component sync

### ISSUE THREAD

**Issue by ForgeGMP** [RAGECOOP/RAGECOOP-V#11]
The Components or variations of the ped clothes, that will fix the bugs with the not displayed correctly clothes

**Comment by Sardelka9515** [comment]
Do you know the native to get/set ped variation?
Ped prop sync is planned. #2

**Comment by Sardelka9515** [comment]
@ForgeGMP I've added it in 13883242e4df1a52c48610fe0f604d69caa55856, fell free to test it in latest nightly build.
