### ISSUE TITLE
OnTick event for resources?

### ISSUE THREAD

**Issue by oldnapalm** [RAGECOOP/RAGECOOP-V#13]
Is there a feature equivalent to "OnTick" to be used in resources?

Like https://github.com/RAGECOOP/RAGECOOP-V/blob/c84e9ee146cae035ca49a1b242e725af03937d6a/Server/ServerScript.cs#L161

**Comment by Sardelka9515** [comment]
The scripting system is being reworked, there's an `OnTick` event for [client side API](https://github.com/RAGECOOP/RAGECOOP-V/blob/212c004d318cf05e86b3770b69bea8ef07560ca4/RageCoop.Client/Scripting/API.cs#L74-L77), but for server side is probaly not necessary due to change to networking mechanism.

**Comment by oldnapalm** [comment]
I use it server side in race resource, any recommendation on how to do it without OnTick?

https://github.com/RAGECOOP/GTAV-RESOURCES/blob/main/Legacy/RaceResource/Race/Race.cs#L86

If you are planning to work on another race resource I will just wait then.

**Comment by Sardelka9515** [comment]
You can use [OnPlayerUpdate](https://github.com/RAGECOOP/RAGECOOP-V/blob/37edef425c5d4722f3a8245b656dab567cac3098/RageCoop.Server/Scripting/API.cs#L33-L36)
Or start a background thread and check it every 10 ms, just remember to terminate it in `OnStop`

**Comment by oldnapalm** [comment]
Thanks.

Could you give an example on how to use OnPlayerUpdate? I can't figure out the arguments, if I use Client it tells me `No overload for OnPlayerUpdate matches delegate EventHandler<Client>`.

**Comment by Sardelka9515** [comment]
EventHandler always has a sender argument, so your handler must accept two arguments,  `(object sender, Client client)` , sender will always be null since it's fired from a static class.

**Comment by Sardelka9515** [comment]
You can then retrieve the player's position with Client.Player.Position

**Comment by Sardelka9515** [comment]
I'll write a wiki for resource creation soon.

**Comment by oldnapalm** [comment]
Thank you, I managed to build it but OnPlayerUpdate never gets called. It works for OnChatMessage.

**Comment by oldnapalm** [comment]
OnPlayerUpdate still does nothing after player connects, maybe I'm missing something?

![2022-06-21 13_18_48-Race - Microsoft Blend para Visual Studio](https://user-images.githubusercontent.com/38410858/174848746-c6596322-667c-46a3-b97d-c2295e7fd6da.png)

**Comment by Sardelka9515** [comment]
![image](https://user-images.githubusercontent.com/106232474/174919350-b99f03eb-097b-4f23-b4d3-2b705e192579.png)
![image](https://user-images.githubusercontent.com/106232474/174919403-d427d81e-9441-4911-8425-04e1370bd6e7.png)
Weird...it's working for me.

**Comment by oldnapalm** [comment]
Apparently I don't know how to build the client, it wasn't sending updates. Now I used the one from nightly builds and it works.

Thanks for your help, much appreciated.

Now I get the crash or error when receiving a native call, but that's another issue (#12).

![2022-06-21 22_28_30-Grand Theft Auto V](https://user-images.githubusercontent.com/38410858/174924230-556162ec-6fcb-4f2a-aba7-d349e4c71b86.png)

```
[ERROR] Caught fatal unhandled exception:
System.InvalidOperationException: Native.Function.Call can only be called from the main thread.
   em GTA.Native.Function.ThrowInvalidOperationExceptionForInvalidNativeCall()
   em GTA.Native.Function.ReturnValueFromNativeIfNotNull[T](UInt64* result)
   em CoopClient.Entities.EntitiesThread.OnTick(Object sender, EventArgs e)
   em SHVDN.Script.MainLoop()
[ERROR] The exception was thrown while executing the script CoopClient.Entities.EntitiesThread.
[WARNING] Aborted script CoopClient.Entities.EntitiesThread.
[ERROR] Script 'CoopClient.Entities.EntitiesThread' is not responding! Aborting ...
[WARNING] Aborted script CoopClient.Entities.EntitiesThread.
```
