### ISSUE TITLE
Dune FAV (If you add it don't close it)

### ISSUE THREAD

**Issue by ForgeGMP** [RAGECOOP/RAGECOOP-V#20]
// DUNE3
                        case 1897744184:
                            return new MuzzleInfo(v.Bones[53].Position, v.Bones[53].ForwardVector);

**Comment by ForgeGMP** [comment]
// DUNE3
                        case 1897744184:
                            return new MuzzleInfo(v.Bones[42].Position, v.Bones[42].ForwardVector);
                        
If the car have the grenade launcher this is the bone

**Comment by Sardelka9515** [comment]
74a22652008cc7d17201be0ea677d5da95e16a11
