### ISSUE TITLE
Server bound 0.0.0.0:4499

### ISSUE THREAD

**Issue by archonis83** [RAGECOOP/RAGECOOP-V#30]
Starting the server does not pull correct ip information. Just reads 0.0.0.0

**Comment by oldnapalm** [comment]
This is normal. If you enable `AnnounceSelf` in Settings.xml it will show your IP
`Your public IP is x.x.x.x, announcing to master server...`

**Comment by Sardelka9515** [comment]
> Starting the server does not pull correct ip information. Just reads 0.0.0.0

@oldnapalm was right, 0.0.0.0 means it's listening on all network interfaces (Wi-Fi, Ethernet...)

It will fetch your public IP from ipinfo.io if AnnounceSelf is set to true(but your server will not be reachable unless the port has been forwarded). If you want to know your private address, type ipconfig in command prompt to see it

**Comment by archonis83** [comment]
Thanks everyone. I being a network guy it threw me off. I did get it
working.
