### ISSUE TITLE
Not quite an issue, buuut...

### ISSUE THREAD

**Issue by AliceTS1337** [RAGECOOP/RAGECOOP-V#34]
Is there any possibility that you'd make RAGECOOP for GTA IV as well? :)

**Comment by ForgeGMP** [comment]
GTA IV have tons of multiplayers man, even have a LAN multiplayer oficial from rockstar

**Comment by Sardelka9515** [comment]
Yes, GTAC is a popular option as well

**Comment by AliceTS1337** [comment]
"Tons" of multiplayers is a bit of an overstatement????????????? GTAC doesn't really have the best of sync - LAN play is not possible with the latest version of the game, LAN play with XLLN is sort of possible but the XLLN app has some bugs and there's an internal bug where the lobby data does not reset properly, causing an issue with the "Next Game" panel.

IV:MP does not utilize the internal netcode.
GTAC does utilize it, but the sync is bad + bugs + crashes.
CitizenIV does utilize it, but does not use the original game network scripts.

What else is there? I cannot recall there being "tons" of multiplayer mods "man" because there are not. Nobody is willing to make them. 

Please forward me to one that is actively updated and one that isn't a mess. A multiplayer for version 1.2.0.43 would be great, ta.
