### ISSUE TITLE
Addon Jet Weapon Sync

### ISSUE THREAD

**Issue by Hydraxonn** [RAGECOOP/RAGECOOP-V#40]
Here I have a selection of 10 addon planes that all have cannons that need to be synced. Ryze from the Discord server and I went through and got the muzzle data for them. These are 10 of the most popular addon jets, so it should help several people get their modded games to sync. The data is here, as follows. 

                        // f14a2
                        case -848721350:
                            return 48;
                        
                        // f15e
                        case 881261972:
                            return 32;
                        
                        // f16c
                        case -2051171080:
                            return 25;
                        
                        // F22A
                        case 2061630439:
                            return 14;
                        
                        // f35c
                        case -343547392:
                            return 44;
                        
                        // mig29a
                        case 513887552:
                            return 18;
                        
                        // su30sm
                        case -733985185:
                            return 34;
                        
                        // su33
                        case -722216722:
                            return 34;
                        
                        // su35s
                        case -268602544:
                            return 28;
                        
                        // su57
                        case 1490050781:
                            return 21;
                        

Looking at the other issues that have added weapon sync, it looks like I'm missing some code here. If you need  any more  info to get these weapons synced, please reach out!
Thanks again for your hard work and dedication.

**Comment by Sardelka9515** [comment]
The code has been changed, your data has no problem
