### ISSUE TITLE
How do I make it work so we can play locally, on local network? OR get a public key?

### ISSUE THREAD

**Issue by webtomek** [RAGECOOP/RAGECOOP-V#47]
I just want to play with my GF. 
I opened a port, I started up the server, I let it through the firewall, I did EVERYTHING I possibly could, yet when she tries to connect, it throws an error saying it couldn't get the public key... I look that up on google, and I get nothing but an empty wiki, and a non existing website (ragecoop.online).

Like what am I supposed to do?

**Comment by mr-mods-yg** [comment]
you can make a LAN server with Hamachi Server

**Comment by webtomek** [comment]
About 2 and a half months later we gave up about it.

But thanks for reminding me of this issue, now I can 100% tell that not a single dev or so called "contributor" gives a flying fuck to atleast answer, nor here, nor in discord.

But the "buy me a coffee" and "support us" links are sitting out there. I feel the irony 😄

**Comment by rhodman** [comment]
> I just want to play with my GF. I opened a port, I started up the server, I let it through the firewall, I did EVERYTHING I possibly could, yet when she tries to connect, it throws an error saying it couldn't get the public key... I look that up on google, and I get nothing but an empty wiki, and a non existing website (ragecoop.online).
> 
> Like what am I supposed to do?

I just spent several days with exactly the same issue, always getting "failed to retrive public key" and I found a solution a few minutes ago: while the server itself tells you a certain ip address, that is not necessarily the one that you need to connect. it was always telling me about x.x.x.15 but I had to use x.x.x.29 to connect. check your ifconfig or ipconfig for additional network addresses. in my case the server was printing the wireless-address but was requiring the lan-address.

this might not be the exact same issue for you, but after a desperate search for answers and not finding any (like you) this is the solution that worked for me

**Comment by blankuser48** [comment]
I had a similar issue with not being able to get the public key and i fixed it by enabling announce self in the config. If you want to make sure no one can join without permission follow the instruction at the bottom of the wiki for setting a password

Edit: Typo

**Comment by webtomek** [comment]
Hi, thanks for your comment, but I've abandoned this thing.
I'm glad if it worked for you tho, hopefully if someone has the same issue, they'll see your comment.
