### ISSUE TITLE
LAN?

### ISSUE THREAD

**Issue by ThanosAtha** [RAGECOOP/RAGECOOP-V#55]
Can I host LAN game server???? Default server ip is 0.0.0.0:4499, how to change it?

**Comment by oldnapalm** [comment]
Use the LAN IP, 0.0.0.0 means you can reach the server through any network interface.

![265561045-30c5267f-22e6-48c5-981d-2122e40490cc](https://github.com/RAGECOOP/RAGECOOP-V/assets/38410858/a4242310-c24e-4639-a304-37c00b0c3513)
