### ISSUE TITLE
Pause hotkey doesn't work

### ISSUE THREAD

**Issue by Katsute** [RAGECOOP/RAGECOOP-V#57]
GTA V allows users to set the hotkey to open the pause menu, by default this is the <kbd>P</kbd> key. In the latest update (v1.4.0) only the <kbd>Escape</kbd> key allows users to open the pause menu, it doesn't take into account the pause hotkey that users can set in the settings.

https://github.com/RAGECOOP/RAGECOOP-V/blob/98a593daae47e2ccaadc67aaececc32ad7de4e79/Client/Main.cs#L173-L175

**Comment by EntenKoeniq** [comment]
Changed with the upcoming update 1.4.1
