### ISSUE TITLE
death effect is OFF

### ISSUE THREAD

**Issue by KazeeKEN** [RAGECOOP/RAGECOOP-V#59]
Can U see my variant?  Work 50/50 for Freemodel character

if (Game.Player.Character.IsDead || Game.Player.Character.Health <= 100) //Game.Player.Character.IsDead
            {
                Function.Call(Hash.STOP_CURRENT_PLAYING_AMBIENT_SPEECH, Game.Player.Character.Handle);
                Function.Call(Hash._SET_PLAYER_INVINCIBLE_KEEP_RAGDOLL_ENABLED, Game.Player.Character.Handle, true);
                Function.Call(Hash.DISABLE_CONTROL_ACTION, 24);
                
                Function.Call(Hash.SET_FADE_OUT_AFTER_ARREST, false);
                Function.Call(Hash.SET_FADE_IN_AFTER_LOAD, false);

                
                Function.Call(Hash.IGNORE_NEXT_RESTART, true); 
                Function.Call(Hash.DISABLE_HOSPITAL_RESTART, true); 
                Function.Call(Hash.SET_FADE_OUT_AFTER_DEATH, false); 
                Function.Call(Hash.CLEAR_PLAYER_WANTED_LEVEL, Game.Player.Character); 
                Game.Player.Character.Health = 200; 
            }

**Comment by oldnapalm** [comment]
Tried `Function.Call(Hash.ANIMPOSTFX_STOP, "DeathFailOut");`?

**Comment by KazeeKEN** [comment]
Not work

**Comment by oldnapalm** [comment]
Maybe you need to call OnTick

```
if (Function.Call<bool>(Hash.ANIMPOSTFX_IS_RUNNING, "DeathFailOut"))
{
    Function.Call(Hash.ANIMPOSTFX_STOP, "DeathFailOut");
}
```

**Comment by KazeeKEN** [comment]
> Maybe you need to call OnTick
> 
> ```
> if (Function.Call<bool>(Hash.ANIMPOSTFX_IS_RUNNING, "DeathFailOut"))
> {
>     Function.Call(Hash.ANIMPOSTFX_STOP, "DeathFailOut");
> }
> ```

Notwork for Freemodel character ))
