### ISSUE TITLE
Crash on Load with V1.4.0

### ISSUE THREAD

**Issue by Hayden-Purificato** [RAGECOOP/RAGECOOP-V#60]
Title says it all. While loading in, fairly late in the process, my game dies. I can provide you with logs, mod lists, gameconfig and dlclist xmls, whatever you need.

**Comment by EntenKoeniq** [comment]
Hello, can you start the game with administrator and after that please send the file "ScriptHookVDotNet.log".

**Comment by Hayden-Purificato** [comment]
Just tried on 1.41 and still get the same crash. here's my ScriptHookVDotNet.log. not sure how much help it'll be!

[ScriptHookVDotNet.log](https://github.com/RAGECOOP/RAGECOOP-V/files/8516878/ScriptHookVDotNet.log)

**Comment by Hayden-Purificato** [comment]
just tried it with a clean scripts folder and it still crashes immediately after the copyright/disclaimer text appears. Next I'll try removing my ASI mods and see if that fixes it. if not, it may be my dlclist or gameconfig, maybe dilapidated's PoolManager.asi can help me.

**Comment by Hayden-Purificato** [comment]
interestingly, when I run the game my scripthookvdotnet.log doesn't update. Odd considering when I remove RAGECoop it loads fine, so it MUST be SHVDN related...

**Comment by Hayden-Purificato** [comment]
Alright I seem to have fixed it. I removed my scripts folder, copied in the one from the zip in the gta5-mods release, and then ran the game. Ran fine with no issues. so then I dragged my old scripts folder in as well, making sure to not overwrite any files. And now it works. I'm gonna chalk this one up to being an issue with my game, sorry to take up your time!
