### ISSUE TITLE
Stromberg Weapons

### ISSUE THREAD

**Issue by ForgeGMP** [RAGECOOP/RAGECOOP-V#9]
// Turrets

                        // STROMBERG
                        case 886810209:
                            i=Main.Ticked%2==0 ? 85 : 84;
                            return new MuzzleInfo(v.Bones[i].Position, v.Bones[i].ForwardVector);
                        

// Missiles

                        // STROMBERG
                        case 886810209:
                            i=Main.Ticked%2==0 ? 53 : 58;
                            return new MuzzleInfo(v.Bones[i].Position, v.Bones[i].ForwardVector);
                        
// Missiles 2

                        // STROMBERG
                        case 886810209:
                            i=Main.Ticked%2==0 ? 54 : 57;
                            return new MuzzleInfo(v.Bones[i].Position, v.Bones[i].ForwardVector);
                        

// Missiles 3

                        // STROMBERG
                        case 886810209:
                            i=Main.Ticked%2==0 ? 55 : 56;
                            return new MuzzleInfo(v.Bones[i].Position, v.Bones[i].ForwardVector);
                        

// Note: 
This car raises a compartment for the missiles

// Compartment

                        // STROMBERG
                        case 886810209:
                            i=Main.Ticked%2==0 ? 59 : 61;
                            return new MuzzleInfo(v.Bones[i].Position, v.Bones[i].ForwardVector);

**Comment by Sardelka9515** [comment]
@ForgeGMP  Thanks.
BTW, you don't have to add missiles, because projectiles are already synchronized.

**Comment by Hayden-Purificato** [comment]
is this still open? the Vehicle weapon sync issue says the Stromberg syncs correctly...

**Comment by Sardelka9515** [comment]
The missile bay sync is missing, so I'll leave it open for now
